# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fa1eb94c-fdb5-4998-85ea-b3ba3c63fa90";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fa1eb94c-fdb5-4998-85ea-b3ba3c63fa90".device = "/dev/disk/by-uuid/fa1eb94c-fdb5-4998-85ea-b3ba3c63fa90";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4DCC-98F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3c393919-8ae8-4d4c-b93c-849e9a1e6562"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
