# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-05a83eae-080f-4a59-93b7-cb5813c5f207";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-05a83eae-080f-4a59-93b7-cb5813c5f207".device = "/dev/disk/by-uuid/05a83eae-080f-4a59-93b7-cb5813c5f207";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/77F6-E910";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-622ace97-1f45-4926-92fb-117ee1d697d4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
